sass:
  sass_dir: assets/_scss
  style: compressed

markdown: kramdown

kramdown:
  parse_block_html: false

exclude:
- README.md
- Makefile
- wiki

# site configuration
base: http://opendatatoolkit.zognet.net

# default values
defaults:
-
  scope:
    path: ""
  values:
    layout: default
-
  scope:
    path: "en"
  values:
    locale: en
-
  scope:
    path: "es"
  values:
    locale: es
-
  scope:
    path: "fr"
  values:
    locale: fr

# language localization
lang:
  locales:
    - [ en, English ]
    - [ es, Espa&ntilde;ol ]
    - [ fr, Fran&ccedil;ais ]
  en:
    title: "Worldbank Open Government Data Toolkit"
    description: "This section of the toolkit provides a summary of the essential elements of open government data, starting with its definition and covering issues from open data portals, applications that use open data, the benefits of open data, open data policy declarations, learning resources and technical assistance resources for open data."
    abstract: "Free and open access to the world’s most comprehensive collection of economic and development data. Browse, map, graph, or download data by country, topic on over 4,000 indicators.  Available in English, Spanish, French, Chinese and Arabic."
    localeprefix: "This page in"
    sidebar:
      - {hdr: h2, link: /en/index.html, title: Open Government Data Toolkit }
      - {hdr: h3, link: /en/open-data-nutshell.html, title: Open Data in a Nutshell }
      - {hdr: h3, link: /en/essentials.html, title: Open Data Essentials }
      - {hdr: h3, link: /en/technology.html, title: Technology Options }
      - {hdr: h3, link: /en/demand.html, title: Demand and Engagement }
      - {hdr: h3, link: /en/supply.html, title: Supply and Quality of Data }
      - {hdr: h3, link: /en/odra.html, title: Readiness Assessment Tool }
      - {hdr: h3, link: /en/technical-assistance.html, title: Technical Assistance }
